language: node_js
cache:
  directories:
    - ~/.npm
  node_js:
    - '10'
git: 
  depth: 3
script:
  - yarn build

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/
  target-branch: master
  commit_message: "Deploy release ${TRAVIS_TAG}"
on:
    branch: dev